In [18]:
import pandas as pd
import numpy as np
from pandas_datareader import data as wb

In [2]:
import yfinance as yf

In [11]:
start = "2018-01-01"
end = "2023-01-01"

BAJIO = yf.download("BBAJIOO.MX", start, end)
GFNORTE = yf.download("GFNORTEO.MX", start, end)
GENTERA = yf.download("GENTERA.MX", start, end)
TELEVISA = yf.download("TLEVISACPO.MX", start, end)
MEGA = yf.download("MEGACPO.MX", start, end)
AMX = yf.download("AMXB.MX", start, end)
GCC = yf.download("GCC.MX", start, end)
CEMEX = yf.download("CEMEXCPO.MX", start, end)
ASUR = yf.download("ASURB.MX", start, end)
GAP = yf.download("GAPB.MX", start, end)
GMXT = yf.download("GMXT.MX", start, end)
TRAXION = yf.download("TRAXIONA.MX", start, end)
VOLARIS = yf.download("VOLARA.MX", start, end)
KIMBER = yf.download("KIMBERA.MX", start, end)
ARCA = yf.download("AC.MX", start, end)
CUERVO = yf.download("CUERVO.MX", start, end)
HERDEZ = yf.download("HERDEZ.MX", start, end)
GRUMA = yf.download("GRUMAB.MX", start, end)
BIMBO = yf.download("BIMBOA.MX", start, end)
LABB = yf.download("LABB.MX", start, end)
LACOMER = yf.download("LACOMERUBC.MX", start, end)
CHEDRAUI = yf.download("CHDRAUIB.MX", start, end)
FEMSA = yf.download("FEMSAUBD.MX", start, end)
LIVERPOOL = yf.download("LIVEPOLC-1.MX", start, end)
ALPEK = yf.download("ALPEKA.MX", start, end)
NEMAK = yf.download("NEMAKA.MX", start, end)
FUNO = yf.download("FUNO11.MX", start, end)
DANHOS = yf.download("DANHOS13.MX", start, end)
TERRA = yf.download("TERRA13.MX", start, end)
PROLOGIS = yf.download("FIBRAPL14.MX", start, end)
MACQUARIE = yf.download("FIBRAMQ12.MX", start, end)
VESTA = yf.download("VESTA.MX", start, end)
OPSIMEX = yf.download("SITES1A-1.MX", start, end)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [13]:
tickers= [BAJIO, GFNORTE, GENTERA, TELEVISA, MEGA, AMX, GCC, CEMEX, ASUR, GAP, GMXT, TRAXION, VOLARIS, KIMBER, ARCA, CUERVO, HERDEZ, GRUMA, BIMBO, LABB, LACOMER, CHEDRAUI, FEMSA, LIVERPOOL, ALPEK, NEMAK, FUNO, DANHOS, TERRA, PROLOGIS, MACQUARIE, VESTA, OPSIMEX]

In [24]:
import matplotlib.pyplot as plt
from pylab import plot

import seaborn as sns

In [29]:
type(tickers)

list

In [30]:
serie = pd.Series(tickers)

In [31]:
type(serie)

pandas.core.series.Series

In [32]:
lista = serie.tolist()

In [33]:
type(lista)

list

In [34]:
lista

[                 Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  35.930000  37.000000  35.500000  36.919998  26.368223   969250
 2018-01-03  37.000000  37.000000  36.200001  36.439999  26.025406   760640
 2018-01-04  37.000000  37.000000  35.500000  36.330002  25.946848   494018
 2018-01-05  36.330002  37.000000  36.330002  36.880001  26.339659   687554
 2018-01-08  36.889999  36.980000  35.820000  36.529999  26.089684   435880
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  63.990002  63.990002  63.000000  63.599998  59.393234    80934
 2022-12-27  63.500000  63.990002  62.669998  63.490002  59.290512   526572
 2022-12-28  63.910000  63.910000  61.470001  62.080002  57.973774  1165036
 2022-12-29  62.310001  62.950001  61.389999  61.630001  57.553539   971887
 2022-12-30  61.689999  62.389999  61.000000  61.380001  57.320076  1394241

 [1259 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  \
 Date
 2018-01-02  108.000000  108.300003  106.889999  107.370003   81.613335
 2018-01-03  107.110001  109.769997  107.000000  109.430000   83.179169
 2018-01-04  108.900002  110.589996  108.900002  109.519997   83.247574
 2018-01-05  109.790001  111.720001  108.720001  110.040001   83.642830
 2018-01-08  109.209999  112.209999  108.900002  109.419998   83.171570
 ...                ...         ...         ...         ...         ...
 2022-12-26  148.429993  148.539993  146.679993  146.679993  138.646164
 2022-12-27  146.610001  149.000000  146.410004  147.009995  138.958084
 2022-12-28  147.199997  147.210007  144.509995  144.850006  136.916412
 2022-12-29  144.710007  145.889999  143.169998  143.429993  135.574173
 2022-12-30  143.649994  144.490005  139.300003  140.240005  132.558899

              Volume
 Date
 2018-01-02  4626737
 2018-01-03  4327398
 2018-01-04  5296469
 2018-01-05  5512784
 2018-01-08  3969470
 ...             ...
 2022-12-26   121499
 2022-12-27  1688425
 2022-12-28  2308858
 2022-12-29  1478067
 2022-12-30  4867037

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  16.480000  16.480000  16.190001  16.350000  14.329592  2148506
 2018-01-03  16.389999  16.430000  16.020000  16.129999  14.136778  3655689
 2018-01-04  16.190001  17.290001  16.190001  17.209999  15.083318  9383592
 2018-01-05  17.290001  17.510000  17.120001  17.379999  15.232312  7481547
 2018-01-08  17.420000  17.549999  16.850000  17.000000  14.899269  7585717
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  22.290001  23.000000  22.290001  22.510000  21.885141   483032
 2022-12-27  22.790001  23.000000  22.320000  22.500000  21.875420  1464500
 2022-12-28  22.430000  22.709999  22.000000  22.129999  21.515690  1363545
 2022-12-29  21.959999  22.350000  21.680000  21.830000  21.224018   719473
 2022-12-30  21.940001  22.400000  21.320000  21.980000  21.369854  1410097

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  73.570000  75.989998  73.099998  75.339996  71.540077  2119696
 2018-01-03  75.709999  75.730003  73.660004  74.849998  71.074791  2349634
 2018-01-04  75.500000  75.500000  73.519997  74.089996  70.353119  2121314
 2018-01-05  74.540001  75.010002  73.599998  74.250000  70.505066  1551487
 2018-01-08  74.430000  74.980003  73.830002  74.370003  70.619003  2108847
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  18.440001  18.670000  18.209999  18.299999  17.922791   265923
 2022-12-27  18.299999  18.420000  17.950001  17.950001  17.580008  2097673
 2022-12-28  17.910000  18.160000  17.459999  17.469999  17.109900  3158835
 2022-12-29  17.480000  18.250000  17.450001  18.000000  17.628975  6937475
 2022-12-30  17.879999  18.049999  17.629999  17.700001  17.335159  3479608

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  80.010002  82.260002  79.580002  80.949997  64.574738   192326
 2018-01-03  82.500000  83.989998  81.169998  82.459999  65.779289   805240
 2018-01-04  82.220001  83.980003  81.059998  81.410004  64.941704   175968
 2018-01-05  81.500000  85.089996  80.980003  81.809998  65.260780   437107
 2018-01-08  82.000000  83.000000  81.019997  81.709999  65.180992  2208933
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  53.279999  53.630001  53.279999  53.299999  49.826466     3746
 2022-12-27  53.880001  53.880001  52.139999  52.660000  49.228172   206290
 2022-12-28  53.509998  53.509998  51.080002  51.990002  48.601837   447565
 2022-12-29  52.180000  52.480000  50.590000  51.990002  48.601837  1165214
 2022-12-30  51.009998  52.310001  50.830002  51.869999  48.489655   153827

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close  Volume
 Date
 2018-01-02  17.000000  17.000000  17.000000  17.000000  14.627373    8937
 2018-01-03  17.510000  17.510000  17.030001  17.000000  14.627373      25
 2018-01-04  17.500000  17.500000  17.500000  17.000000  14.627373       9
 2018-01-05  17.020000  17.020000  17.020000  17.000000  14.627373      10
 2018-01-08  17.000000  17.000000  17.000000  17.000000  14.627373       0
 ...               ...        ...        ...        ...        ...     ...
 2022-12-26  17.799999  17.799999  17.799999  17.799999  17.380102       0
 2022-12-27  17.799999  17.799999  17.799999  17.799999  17.380102       0
 2022-12-28  17.799999  17.799999  17.799999  17.799999  17.380102       0
 2022-12-29  18.200001  18.200001  18.200001  18.200001  17.770668     649
 2022-12-30  18.200001  18.200001  18.200001  18.200001  17.770668       0

 [1259 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  Volume
 Date
 2018-01-02   89.519997   93.000000   89.459999   92.959999   88.751465   10940
 2018-01-03   92.959999   93.000000   91.000000   92.599998   88.407761   47397
 2018-01-04   91.139999   92.309998   91.120003   92.000000   87.834923   51983
 2018-01-05   92.000000   92.879997   92.000000   92.860001   88.655998  244196
 2018-01-08   92.000000   93.029999   92.000000   92.940002   88.732376   51516
 ...                ...         ...         ...         ...         ...     ...
 2022-12-26  131.899994  131.940002  131.020004  131.899994  130.659515   38701
 2022-12-27  132.169998  132.929993  130.610001  131.899994  130.659515  182307
 2022-12-28  131.899994  131.899994  127.000000  128.800003  127.588684   75225
 2022-12-29  128.839996  130.979996  128.839996  130.000000  128.777390  118341
 2022-12-30  130.539993  131.220001  128.270004  129.789993  128.569366   72389

 [1259 rows x 6 columns],
              Open   High    Low  Close  Adj Close    Volume
 Date
 2018-01-02  14.77  15.13  14.61  15.07  14.689502  19881071
 2018-01-03  15.07  15.43  15.02  15.25  14.864958  27899237
 2018-01-04  15.32  15.49  15.28  15.39  15.001423  26302699
 2018-01-05  15.42  15.51  15.15  15.18  14.796725  25383892
 2018-01-08  15.28  15.29  15.09  15.15  14.767483  23971658
 ...           ...    ...    ...    ...        ...       ...
 2022-12-26   8.24   8.31   8.16   8.16   8.160000   2341380
 2022-12-27   8.14   8.37   8.12   8.19   8.190000   8754457
 2022-12-28   8.19   8.23   7.99   8.04   8.040000  13693814
 2022-12-29   8.01   8.21   8.01   8.13   8.130000  14018634
 2022-12-30   8.07   8.11   7.83   7.92   7.920000  27617661

 [1259 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  Volume
 Date
 2018-01-02  358.070007  377.579987  356.350006  371.579987  330.931396  372991
 2018-01-03  380.000000  380.000000  367.859985  371.480011  330.842377  313236
 2018-01-04  375.000000  375.000000  365.739990  370.049988  329.568756  290419
 2018-01-05  370.049988  373.000000  366.010010  368.609985  328.286316  328509
 2018-01-08  368.809998  374.980011  365.269989  367.660004  327.440186  320101
 ...                ...         ...         ...         ...         ...     ...
 2022-12-26  486.350006  487.049988  477.510010  478.269989  468.937683   19140
 2022-12-27  481.019989  492.869995  481.019989  488.140015  478.615112   97294
 2022-12-28  490.000000  491.970001  472.279999  472.820007  463.594025  302144
 2022-12-29  476.000000  478.420013  468.160004  469.100006  459.946625  176919
 2022-12-30  467.950012  472.459991  452.010010  454.010010  445.151062  308435

 [1259 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  \
 Date
 2018-01-02  202.270004  204.949997  201.210007  203.220001  149.274826
 2018-01-03  202.550003  205.199997  202.550003  204.699997  150.361923
 2018-01-04  202.500000  207.000000  201.899994  205.809998  151.177292
 2018-01-05  206.000000  208.960007  205.100006  206.089996  151.382965
 2018-01-08  207.000000  208.539993  205.050003  206.369995  151.588669
 ...                ...         ...         ...         ...         ...
 2022-12-26  300.279999  301.200012  291.790009  292.920013  272.312012
 2022-12-27  295.700012  301.399994  290.019989  296.649994  275.779572
 2022-12-28  297.420013  297.880005  289.739990  290.089996  283.439819
 2022-12-29  293.690002  295.000000  286.160004  288.839996  282.218475
 2022-12-30  288.420013  289.200012  277.149994  279.399994  272.994873

              Volume
 Date
 2018-01-02  1004982
 2018-01-03   890099
 2018-01-04   585899
 2018-01-05  1227414
 2018-01-08   881226
 ...             ...
 2022-12-26    30538
 2022-12-27   423682
 2022-12-28   393492
 2022-12-29   405113
 2022-12-30   647374

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close  Volume
 Date
 2018-01-02  29.799999  30.190001  29.799999  30.010000  23.740499  610736
 2018-01-03  30.600000  30.600000  30.110001  30.209999  23.898712  429255
 2018-01-04  30.100000  30.889999  30.100000  30.600000  24.207235  476350
 2018-01-05  30.570000  31.290001  30.250000  31.010000  24.531584  800611
 2018-01-08  31.160000  31.209999  30.549999  31.090000  24.594872  210921
 ...               ...        ...        ...        ...        ...     ...
 2022-12-26  37.619999  37.959999  37.619999  37.959999  37.024677     347
 2022-12-27  37.480000  37.540001  37.360001  37.540001  36.615028   48921
 2022-12-28  38.490002  38.490002  37.470001  37.599998  36.673550   13263
 2022-12-29  37.650002  37.650002  37.180000  37.349998  36.429710    4867
 2022-12-30  37.029999  38.099998  37.020000  37.900002  36.966160   35327

 [1258 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  15.400000  15.760000  15.310000  15.750000  15.750000   203319
 2018-01-03  15.870000  16.250000  15.680000  16.120001  16.120001   588306
 2018-01-04  16.070000  16.250000  15.710000  16.070000  16.070000   217304
 2018-01-05  16.080000  16.299999  15.720000  16.110001  16.110001   333997
 2018-01-08  16.100000  16.150000  15.400000  16.020000  16.020000  1942006
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  28.480000  29.000000  28.450001  28.709999  28.709999    58848
 2022-12-27  28.820000  29.000000  28.240000  28.670000  28.670000    81733
 2022-12-28  28.770000  28.950001  27.650000  28.930000  28.930000   158021
 2022-12-29  28.680000  29.219999  27.000000  27.160000  27.160000   349612
 2022-12-30  27.450001  27.590000  26.200001  27.000000  27.000000   437710

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  15.780000  16.330000  15.710000  15.950000  15.950000  1180567
 2018-01-03  15.920000  16.100000  15.400000  15.980000  15.980000  2170013
 2018-01-04  16.090000  16.299999  16.020000  16.080000  16.080000  1632030
 2018-01-05  16.280001  16.340000  16.030001  16.080000  16.080000  2999400
 2018-01-08  16.160000  16.180000  15.480000  15.750000  15.750000  3026532
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  16.660000  17.100000  16.660000  16.940001  16.940001   307747
 2022-12-27  16.940001  16.940001  16.379999  16.520000  16.520000  1558540
 2022-12-28  16.500000  16.520000  15.520000  15.590000  15.590000  2051369
 2022-12-29  15.650000  16.480000  15.650000  16.299999  16.299999  2439359
 2022-12-30  16.280001  16.459999  15.890000  16.230000  16.230000  1945103

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  35.299999  35.820000  34.209999  35.639999  26.640680  3425929
 2018-01-03  35.650002  35.790001  34.009998  34.209999  25.571768  2141639
 2018-01-04  34.380001  34.930000  34.380001  34.810001  26.020264  1849850
 2018-01-05  34.889999  34.889999  33.770000  34.360001  25.683893  1976068
 2018-01-08  34.419998  34.869999  34.020000  34.500000  25.788540  3835564
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  33.849998  34.250000  33.790001  34.000000  32.538990   247925
 2022-12-27  33.750000  34.389999  33.750000  33.900002  32.443291  1430433
 2022-12-28  33.820000  34.020000  33.520000  33.849998  32.395435  2152237
 2022-12-29  33.900002  34.599998  33.599998  33.830002  32.376297  2569797
 2022-12-30  33.990002  34.000000  32.540001  33.070000  31.648954  2912534

 [1259 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  \
 Date
 2018-01-02  136.490005  138.380005  134.119995  138.160004  112.918770
 2018-01-03  138.990005  138.990005  134.440002  134.699997  110.090866
 2018-01-04  134.699997  135.289993  133.779999  133.860001  109.404358
 2018-01-05  133.850006  135.820007  133.830002  134.800003  110.172600
 2018-01-08  135.000000  136.000000  133.759995  134.910004  110.262520
 ...                ...         ...         ...         ...         ...
 2022-12-26  164.050003  164.880005  160.529999  160.550003  157.308441
 2022-12-27  161.839996  165.300003  161.550003  161.759995  158.494003
 2022-12-28  162.580002  164.470001  160.369995  160.990005  157.739563
 2022-12-29  162.050003  162.179993  159.080002  159.080002  155.868118
 2022-12-30  160.940002  160.940002  157.100006  158.039993  154.849106

              Volume
 Date
 2018-01-02   588099
 2018-01-03   986153
 2018-01-04  1332384
 2018-01-05   704845
 2018-01-08   904098
 ...             ...
 2022-12-26    67851
 2022-12-27   447604
 2022-12-28   736092
 2022-12-29   671898
 2022-12-30  1315664

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  31.950001  32.880001  31.600000  32.720001  30.267290   926085
 2018-01-03  33.000000  33.200001  32.000000  32.869999  30.406046  1105876
 2018-01-04  33.200001  33.200001  32.000000  32.700001  30.248787  2028577
 2018-01-05  32.509998  33.119999  32.509998  33.040001  30.563303   777396
 2018-01-08  33.119999  33.250000  32.750000  33.009998  30.535549  1456809
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  43.139999  43.500000  42.900002  43.500000  43.011860    20696
 2022-12-27  43.160000  43.279999  42.669998  43.099998  42.616348   571904
 2022-12-28  42.849998  42.970001  42.099998  42.660000  42.181286   576794
 2022-12-29  42.779999  43.110001  41.830002  42.509998  42.032970   398795
 2022-12-30  42.560001  42.560001  42.070000  42.549999  42.072521  1016331

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close  Volume
 Date
 2018-01-02  45.680000  45.680000  44.700001  45.380001  38.578178   54339
 2018-01-03  45.549999  46.119999  45.500000  45.910000  39.028736   44607
 2018-01-04  45.919998  45.919998  45.049999  45.590000  38.756699   75744
 2018-01-05  45.750000  47.549999  44.810001  46.680000  39.683323  174029
 2018-01-08  46.779999  48.000000  46.150002  46.680000  39.683323  549191
 ...               ...        ...        ...        ...        ...     ...
 2022-12-26  41.799999  41.820000  41.299999  41.529999  40.470337   43715
 2022-12-27  41.779999  42.000000  41.509998  42.000000  40.928345   46540
 2022-12-28  42.000000  42.980000  41.590000  42.529999  41.444820   66038
 2022-12-29  42.980000  43.200001  42.619999  43.080002  41.980789   49969
 2022-12-30  43.349998  43.799999  42.770000  43.529999  42.419304   59325

 [1259 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  Volume
 Date
 2018-01-02  249.300003  249.899994  245.899994  248.130005  215.570114  419896
 2018-01-03  247.559998  249.979996  243.500000  247.050003  214.631836  438690
 2018-01-04  248.279999  249.789993  245.000000  245.500000  213.285217  645028
 2018-01-05  246.720001  252.240005  244.250000  250.779999  217.872406  499722
 2018-01-08  251.399994  252.300003  247.000000  248.779999  216.134842  595552
 ...                ...         ...         ...         ...         ...     ...
 2022-12-26  259.799988  277.000000  259.799988  269.700012  264.545044  292100
 2022-12-27  269.380005  271.880005  263.410004  268.070007  262.946198  230455
 2022-12-28  268.049988  268.399994  265.100006  267.250000  262.141846  216166
 2022-12-29  265.910004  271.880005  264.880005  267.970001  262.848083  286496
 2022-12-30  267.820007  268.299988  259.450012  260.320007  255.344330  357356

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  43.720001  43.750000  42.910000  43.380001  39.843021  1626731
 2018-01-03  43.220001  43.650002  43.099998  43.400002  39.861397  1230572
 2018-01-04  43.650002  44.000000  43.029999  43.669998  40.109367  2341379
 2018-01-05  43.770000  44.000000  43.419998  43.540001  39.989975  3034896
 2018-01-08  43.639999  43.970001  43.110001  43.509998  39.962418  1886857
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  85.949997  87.150002  85.519997  85.739998  85.045532    80008
 2022-12-27  86.000000  88.110001  85.860001  86.739998  86.037430   689505
 2022-12-28  86.849998  86.849998  84.910004  85.610001  84.916588  1010754
 2022-12-29  85.660004  87.519997  83.830002  84.120003  83.438660  1009902
 2022-12-30  84.500000  85.160004  81.849998  82.300003  81.633400  1903721

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close   Volume
 Date
 2018-01-02  20.520000  21.049999  20.520000  20.980000  18.205063   720957
 2018-01-03  21.049999  22.250000  21.049999  21.750000  18.873217  2302631
 2018-01-04  21.850000  22.000000  20.959999  21.049999  18.265804  1864551
 2018-01-05  21.160000  21.309999  20.860001  21.120001  18.326546   978301
 2018-01-08  21.070000  21.570000  21.059999  21.469999  18.630251  1217410
 ...               ...        ...        ...        ...        ...      ...
 2022-12-26  17.070000  17.070000  16.809999  16.850000  16.634478   151391
 2022-12-27  16.730000  17.049999  16.580000  16.920000  16.703583  1435291
 2022-12-28  16.889999  16.889999  16.350000  16.490000  16.279083  1517753
 2022-12-29  16.549999  16.860001  16.309999  16.680000  16.466652  2811609
 2022-12-30  16.690001  17.059999  16.520000  16.870001  16.654222  3761627

 [1259 rows x 6 columns],
                  Open       High        Low      Close  Adj Close  Volume
 Date
 2018-01-02  20.219999  20.490000  20.000000  20.170000  19.538370   41916
 2018-01-03  20.299999  20.299999  20.010000  20.010000  19.383381   57210
 2018-01-04  20.299999  20.299999  19.590000  19.700001  19.083090  229621
 2018-01-05  19.879999  19.879999  19.610001  19.690001  19.073404  626437
 2018-01-08  19.750000  19.830000  19.420000  19.610001  18.995909  501033

In [35]:
data = pd.DataFrame (tickers)

/usr/local/lib/python3.10/dist-packages/pandas/core/internals/construction.py:568: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])

In [37]:
data.to_excel('ALPHA_Returns.xlsx', sheet_name= 'ALPHA', index= False)